language: php

php:
- 5.6
- 7.0
- 7.1
- 7.2
- hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
- composer install --prefer-source

script:
- if [ "$TRAVIS_PHP_VERSION" == "hhvm" ]; then vendor/bin/phpunit; fi
- if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover; fi

after_script:
- bash -c 'if [[ "$TRAVIS_PHP_VERSION" != "hhvm" && "$TRAVIS_PHP_VERSION" != 7* ]]; then php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover; fi;'

notifications:
  slack:
    secure: TBBA8oVly4KuWFN9ztvvYumBzJJKvkQfF1+lJbmkLx8/9mQo2eLG8wKlOjbjL+AkhkHMXCi/ri3OamUbM0GCtKHwtjWIOEVXulrv8Simrn9DBMzxI8ofBF7vr3g746w7qmTo2n/GmGmNTmNf07C+4cuF9IE0xLARSTF1eYw9UbbPE3TABp8M85iOPzNy3Zphw6E31WEDtfKvzXAbElpt+/p0vPgM5oXzIY29v7EgzmzVg5LXI6TQSAx4yK1dvnTUfzTbASceWDWb24e5V74X/XVIS1rzrZoW3P7zOoUenzQlwO6Bp/wgiqcL0Setr8rB41VyRldjSvqSBTYBMAWubwpwUF8ryR1AC0dUxMuN5zxfCgWbYC+J4ntvBaG9tbzoMVkQrOoxbbLlSxcXTwVS4tAN9wgAAk1pVHqmT51xf+xxGJqO2urhdLz6pn2rgs4RC8l6XEw81BK7Ez8woXBRg67xRX7+WgF3lTBbYyZa4MZNfT1diqmFKINol+EtXIaasW+APYlMOIcjT0MRhYaNf450j8+2TbtXFexAMKX5sPacry30Wx38dRHORnKw/mpA6X5QsG/PaDix7xV50+nBGlevXuvojZzPpzZp13qQS5mBU8crFZwbvl6KLx6yx1a+tJwk2SzwmlJRCGuSY8WR4JrBQ3bKzcJ1Ihkxi3vDJOY=
